version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "deps"
    groups:
      nuget-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      nuget-version:
        applies-to: "version-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
    groups:
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      github-actions-version:
        applies-to: "version-updates"
        patterns:
          - "*"
