using System.Globalization;

namespace HS2VoiceReplace;

// Centralizes all end-user-facing strings so UI text, logs, and validation
// messages can be localized without scattering literals across the codebase.
internal static class UiTextCatalog
{
    private readonly record struct Entry(string Ja, string En);

    private static Entry E(string ja, string en) => new(ja, en);

    private static readonly Dictionary<string, Entry> Entries = new(StringComparer.Ordinal)
    {
        // App and top-level commands
        ["app.title"] = E("HS2VoiceReplaceGui", "HS2VoiceReplaceGui"),
        ["button.setup"] = E("依存セットアップ", "Install Dependencies"),
        ["button.extract"] = E("データ抽出", "Extract Data"),
        ["button.deploy"] = E("配備", "Deploy"),
        ["button.undeploy"] = E("配備解除", "Undeploy"),
        ["button.preview"] = E("試聴生成", "Generate Preview"),
        ["button.stop"] = E("停止", "Stop"),
        ["button.conversionSettings"] = E("VC設定", "VC Settings"),
        ["button.range"] = E("範囲調整", "Edit Range"),
        ["button.clear"] = E("クリア", "Clear"),
        ["button.play"] = E("再生", "Play"),
        ["button.browse"] = E("参照", "Browse"),
        ["button.clearPath"] = E("消去", "Clear"),
        ["button.close"] = E("閉じる", "Close"),
        ["button.ok"] = E("OK", "OK"),
        ["button.cancel"] = E("キャンセル", "Cancel"),
        ["button.apply"] = E("適用", "Apply"),
        ["button.reload"] = E("再読込", "Reload"),
        ["button.runAll"] = E("全量変換", "Run Full Conversion"),
        ["button.rebuild"] = E("再作成", "Rebuild"),
        ["button.rebuildRow"] = E("この行を再作成", "Rebuild Row"),
        ["button.discard"] = E("破棄", "Discard"),
        ["button.discardDst"] = E("変換後を破棄", "Discard Output"),
        ["button.playSrc"] = E("元音声を再生", "Play Source"),
        ["button.playDst"] = E("変換後を再生", "Play Output"),
        ["button.playSelection"] = E("選択範囲を再生", "Play Selection"),
        ["button.addRangeExtract"] = E("範囲を切り出して追加", "Add from Range"),
        ["button.rename"] = E("名前変更", "Rename"),
        ["button.deleteToTrash"] = E("ゴミ箱へ移動", "Move to Trash"),
        ["button.restore"] = E("復元", "Restore"),
        ["button.deletePermanent"] = E("完全削除", "Delete Permanently"),
        ["button.playSample"] = E("サンプル再生", "Play Sample"),
        ["checkbox.skipCompleted"] = E("実行済み工程をスキップ", "Skip completed steps"),
        ["checkbox.showTrash"] = E("ゴミ箱を表示", "Show trash"),
        ["menu.settings"] = E("設定", "Settings"),
        ["menu.general"] = E("基本設定...", "General Settings..."),
        ["menu.sampleAudio"] = E("サンプル音声...", "Sample Audio..."),
        ["menu.conversion"] = E("VC設定...", "VC Settings..."),

        // General settings
        ["general.title"] = E("基本設定", "General Settings"),
        ["general.bundledRuntimeRoot"] = E("同梱ランタイムルート（固定）", "Bundled runtime root (fixed)"),
        ["general.outputRoot"] = E("出力ルート（固定）", "Output root (fixed)"),
        ["general.externalToolsRoot"] = E("外部ツールルート（任意）", "External tools root (optional)"),
        ["general.sourceHs2Root"] = E("抽出元HS2フォルダ", "Source HS2 folder"),
        ["general.deployHs2Root"] = E("配備先HS2フォルダ", "Deploy HS2 folder"),
        ["general.uiLanguage"] = E("UI言語", "UI language"),
        ["general.executionOptions"] = E("実行オプション", "Execution options"),
        ["general.languageJapanese"] = E("日本語", "Japanese"),
        ["general.languageEnglish"] = E("英語", "English"),
        ["general.languageBusyMessage"] = E(
            "変換や配備の実行中は UI 言語を変更できません。先に現在の処理を停止してください。",
            "You cannot change the UI language while a job is running. Stop the current job first."),
        ["general.languageBusyTitle"] = E("処理実行中", "Job Running"),
        ["general.languageSwitchError"] = E("UI言語の切り替えエラー", "UI Language Switch Error"),

        // Main screen labels
        ["core.targetPersonality"] = E("差し替え対象性格", "Target personality"),
        ["core.conversionSummary"] = E("変換設定:", "Conversion settings:"),
        ["core.sampleSignature"] = E("サンプル署名:", "Sample signatures:"),
        ["core.sampleSignatureUnavailable"] = E("N:（取得失敗） E:（取得失敗）", "N:(error) E:(error)"),
        ["core.optionalSuffix"] = E("（任意）", "(Optional)"),

        // Sample audio dialog
        ["dialog.sampleAudio.title"] = E("サンプル音声", "Sample Audio"),
        ["dialog.sampleAudio.normalAssignment"] = E("normal 割り当て", "Normal assignment"),
        ["dialog.sampleAudio.eroAssignment"] = E("ero 割り当て", "Ero assignment"),
        ["dialog.sampleAudio.conversionSampleSignature"] = E("変換に使う署名", "Conversion signature"),
        ["dialog.sampleAudio.column.name"] = E("名前", "Name"),
        ["dialog.sampleAudio.column.state"] = E("状態", "State"),
        ["dialog.sampleAudio.column.signature"] = E("署名", "Signature"),
        ["dialog.sampleAudio.column.hashVer"] = E("ハッシュ版", "Hash Ver."),
        ["dialog.sampleAudio.column.length"] = E("長さ[s]", "Length [s]"),
        ["dialog.sampleAudio.column.hz"] = E("Hz", "Hz"),
        ["dialog.sampleAudio.column.ch"] = E("Ch", "Ch"),
        ["dialog.sampleAudio.column.source"] = E("元音声", "Source"),
        ["dialog.sampleAudio.column.range"] = E("切り出し範囲", "Range"),
        ["dialog.sampleAudio.column.extractedAt"] = E("切り出し日時", "Extracted At"),
        ["dialog.sampleAudio.column.lastUsedAt"] = E("最終使用日時", "Last Used"),
        ["dialog.sampleAudio.previewNormal"] = E("試聴（normal）", "Preview (normal)"),
        ["dialog.sampleAudio.previewEro"] = E("試聴（ero）", "Preview (ero)"),
        ["dialog.sampleAudio.previewIsolated"] = E(
            "※ 試聴用ファイルは本番の変換結果とは別フォルダに保存されます。",
            "Preview files are stored separately from the main conversion output."),
        ["dialog.sampleAudio.state.trash"] = E("ゴミ箱", "Trash"),
        ["dialog.sampleAudio.state.active"] = E("有効", "Active"),
        ["dialog.sampleAudio.prompt.name"] = E("サンプル名", "Sample name"),
        ["dialog.sampleAudio.prompt.newName"] = E("新しい名前", "New name"),
        ["dialog.sampleAudio.confirm.deletePermanent"] = E(
            "このサンプル音声を完全に削除します。元に戻せません。続行しますか？",
            "This permanently deletes the sample audio. This cannot be undone. Continue?"),
        ["dialog.confirm"] = E("確認", "Confirm"),
        ["dialog.prompt.enterName"] = E("名前を入力してください。", "Please enter a name."),
        ["dialog.error.add"] = E("サンプル追加エラー", "Add Sample Error"),
        ["dialog.error.rename"] = E("名前変更エラー", "Rename Error"),
        ["dialog.error.delete"] = E("削除エラー", "Delete Error"),
        ["dialog.error.restore"] = E("復元エラー", "Restore Error"),
        ["dialog.error.deletePermanent"] = E("完全削除エラー", "Permanent Delete Error"),
        ["dialog.error.play"] = E("再生エラー", "Playback Error"),

        // Range selector
        ["dialog.rangeEditor.title"] = E("サンプル範囲選択", "Select Sample Range"),
        ["dialog.rangeEditor.input"] = E("入力元: {0}", "Source: {0}"),
        ["dialog.rangeEditor.loading"] = E("波形を読み込み中...", "Loading waveform..."),
        ["dialog.rangeEditor.start"] = E("開始[s]", "Start [s]"),
        ["dialog.rangeEditor.length"] = E("長さ[s]", "Length [s]"),
        ["dialog.rangeEditor.selectionEmpty"] = E("選択範囲: --", "Selection: --"),
        ["dialog.rangeEditor.selection"] = E("選択範囲: {0} - {1} / 全長 {2}", "Selection: {0} - {1} / Total {2}"),
        ["dialog.rangeEditor.loadDone"] = E("波形を読み込みました。", "Waveform loaded."),
        ["dialog.rangeEditor.loadFailed"] = E("波形の読み込みに失敗しました。", "Failed to load waveform."),
        ["dialog.error.waveformLoad"] = E("波形読み込みエラー", "Waveform Load Error"),
        // Conversion grid
        ["dialog.partialGrid.title"] = E("変換一覧", "Conversion Grid"),
        ["dialog.partialGrid.column.relativePath"] = E("相対パス", "Relative Path"),
        ["dialog.partialGrid.column.bucket"] = E("モデル", "Model"),
        ["dialog.partialGrid.column.sourceWav"] = E("元WAV", "Source WAV"),
        ["dialog.partialGrid.column.convertedWav"] = E("変換後WAV", "Converted WAV"),
        ["dialog.partialGrid.column.source"] = E("元", "Source"),
        ["dialog.partialGrid.column.output"] = E("変換後", "Output"),
        ["dialog.partialGrid.column.status"] = E("状態", "Status"),
        ["dialog.partialGrid.column.line"] = E("セリフ", "Line"),
        ["dialog.partialGrid.column.signatureUsed"] = E("使用署名", "Used Signature"),
        ["dialog.partialGrid.column.playSrc"] = E("元を再生", "Play Source"),
        ["dialog.partialGrid.column.playDst"] = E("変換後を再生", "Play Output"),
        ["dialog.partialGrid.column.rebuild"] = E("再作成", "Rebuild"),
        ["dialog.partialGrid.column.discard"] = E("変換後を破棄", "Discard Output"),
        ["dialog.partialGrid.status.runningFull"] = E("全量変換を実行中...", "Running full conversion..."),
        ["dialog.partialGrid.status.completedFull"] = E("全量変換が完了しました。", "Full conversion completed."),
        ["dialog.partialGrid.status.cancelledFull"] = E("全量変換を中止しました。", "Full conversion cancelled."),
        ["dialog.partialGrid.status.converting"] = E("変換中", "Converting"),
        ["dialog.partialGrid.status.discardedAt"] = E("破棄済み {0}", "Discarded {0}"),
        ["dialog.partialGrid.status.doneAt"] = E("完了 {0}", "Completed {0}"),
        ["dialog.partialGrid.status.failed"] = E("失敗", "Failed"),
        ["dialog.partialGrid.status.errorWithMessage"] = E("エラー: {0}", "Error: {0}"),
        ["dialog.partialGrid.status.loadedRows"] = E("読込済み: {0} 行", "Loaded: {0} rows"),
        ["dialog.partialGrid.status.noCancelableWork"] = E("中止できる処理はありません。", "There is no active operation to cancel."),
        ["dialog.partialGrid.status.rebuilding"] = E("再作成中...", "Rebuilding..."),
        ["dialog.partialGrid.status.cancelRequested"] = E("停止を要求しました...", "Stop requested..."),
        ["dialog.partialGrid.status.runRootRequired"] = E("run_root が設定されていません。", "run_root is not set."),
        ["dialog.partialGrid.status.updatedPath"] = E("再作成完了: {0}", "Rebuilt: {0}"),
        ["dialog.partialGrid.status.discardedPath"] = E("破棄しました: {0}", "Discarded: {0}"),
        ["dialog.error.fullConversion"] = E("全量変換エラー", "Full Conversion Error"),
        ["dialog.error.rebuild"] = E("再作成エラー", "Rebuild Error"),
        ["dialog.error.discard"] = E("破棄エラー", "Discard Error"),
        ["dialog.error.playback"] = E("再生エラー", "Playback Error"),
        ["dialog.error.range"] = E("範囲調整エラー", "Range Edit Error"),

        // Status strings
        ["message.notFound"] = E("{0} が見つかりません。", "{0} was not found."),
        ["status.ok"] = E("変換済み", "Converted"),
        ["status.fallbackSrc"] = E("元音声を使用", "Copied from source"),
        ["status.fallbackSilence"] = E("無音で補完", "Filled with silence"),
        ["status.failedRebuild"] = E("失敗（再作成が必要）", "Failed (needs rebuild)"),
        ["status.pending"] = E("未変換", "Pending"),
        ["status.pendingWithOutput"] = E("出力あり（今回の履歴外）", "Output exists (not in current run)"),
        ["status.unknownWithOutput"] = E("出力あり（履歴不明）", "Output exists (history unavailable)"),
        ["status.outputWithRaw"] = E("出力あり（{0}）", "Output exists ({0})"),
        ["status.pendingWithRaw"] = E("未変換（{0}）", "Pending ({0})"),

        // Top-level flow results
        ["setup.completed"] = E("=== 依存セットアップ完了 ===", "=== Dependency Setup Completed ==="),
        ["setup.completedMessage"] = E("依存セットアップが完了しました。", "Dependency setup completed."),
        ["setup.cancelled"] = E("[cancelled] 依存セットアップを停止しました", "[cancelled] Dependency setup stopped."),
        ["setup.error"] = E("依存セットアップエラー", "Dependency Setup Error"),
        ["extract.completed"] = E("=== データ抽出完了 ===", "=== Data Extraction Completed ==="),
        ["extract.completedMessage"] = E("データ抽出が完了しました。次に試聴生成または全量変換を実行できます。", "Data extraction completed. You can now generate a preview or run the full conversion."),
        ["extract.cancelled"] = E("[cancelled] データ抽出を停止しました", "[cancelled] Data extraction stopped."),
        ["extract.error"] = E("データ抽出エラー", "Data Extraction Error"),
        ["preview.completed"] = E("=== 試聴生成完了 ===", "=== Preview Generated ==="),
        ["preview.completedMessage"] = E("試聴用ファイルを生成しました。normal / ero を確認してから全量変換を実行してください。", "Preview files are ready. Check the normal and ero previews before running the full conversion."),
        ["preview.cancelled"] = E("[cancelled] 試聴生成を停止しました", "[cancelled] Preview generation stopped."),
        ["preview.error"] = E("試聴生成エラー", "Preview Generation Error"),
        ["build.completed"] = E("=== 全量変換完了 ===", "=== Full Conversion Completed ==="),
        ["build.cancelled"] = E("[cancelled] 処理を停止しました", "[cancelled] Stopped by user."),
        ["build.notCompleted"] = E("全量変換は最後まで完了していません。", "The full conversion did not complete."),
        ["deploy.completed"] = E("=== 配備完了 ===", "=== Deployment Completed ==="),
        ["deploy.completedMessage"] = E("配備が完了しました。", "Deployment completed."),
        ["deploy.cancelled"] = E("[cancelled] 配備を停止しました", "[cancelled] Deployment stopped."),
        ["deploy.error"] = E("配備エラー", "Deployment Error"),
        ["undeploy.completed"] = E("=== 配備解除完了 ===", "=== Undeploy Completed ==="),
        ["undeploy.completedMessage"] = E("選択中の性格に対応する zipmod と DLL を削除しました。", "Removed the deployed zipmods and DLL for the selected personality."),
        ["undeploy.cancelled"] = E("[cancelled] 配備解除を停止しました", "[cancelled] Undeploy stopped."),
        ["undeploy.error"] = E("配備解除エラー", "Undeploy Error"),

        // Logs
        ["log.seedVcUpdated"] = E("SeedVC 設定を更新しました。", "Updated the SeedVC settings."),
        ["log.sampleSignatureRefreshFailed"] = E("[warn] サンプル署名の更新に失敗しました: {0}", "[warn] Failed to refresh the sample signature: {0}"),
        ["log.sampleRangeUpdated"] = E("サンプル範囲を更新しました: {0} -> {1}", "Updated the sample range: {0} -> {1}"),
        ["log.rangeError"] = E("[error] 範囲調整: {0}", "[error] Range edit: {0}"),
        ["log.playback"] = E("再生: {0}", "Play: {0}"),
        ["log.playbackFailed"] = E("[error] 再生に失敗しました: {0}", "[error] Playback failed: {0}"),
        ["log.embeddedGridInitFailed"] = E("[error] 埋め込みグリッドの初期化に失敗しました: {0}", "[error] Failed to initialize the embedded grid: {0}"),
        ["log.sampleCatalogLoadFailed"] = E("[warn] サンプル一覧の読み込みに失敗しました: {0}", "[warn] Failed to load the sample catalog: {0}"),
        ["log.uiLanguageSwitch"] = E("[error] UI 言語の切り替えに失敗しました: {0}", "[error] Failed to switch the UI language: {0}"),
        ["log.sampleSignature"] = E("サンプル署名: N={0} E={1}", "Sample signatures: N={0} E={1}"),
        ["log.cancelRequested"] = E("[cancel] 停止を要求しました", "[cancel] Stop requested."),
        ["log.adjustedPythonPth"] = E("python._pth を調整しました。", "Adjusted python._pth."),
        ["log.installPip"] = E("pip をインストールしています...", "Installing pip..."),
        ["log.seedVcAlreadyExists"] = E("Seed-VC は既に存在します。", "Seed-VC already exists."),
        ["log.installSeedVcDeps"] = E("Seed-VC の依存関係をインストールしています（時間がかかる場合があります）", "Installing Seed-VC dependencies (this may take a while)."),
        ["log.noNvidiaGpu"] = E("NVIDIA GPU が見つからないため、torch は CPU 版のままにします。", "No NVIDIA GPU detected, so torch will remain on the CPU build."),
        ["log.enableCudaTorch"] = E("NVIDIA GPU を検出しました。CUDA 版 torch をインストールします。", "Detected an NVIDIA GPU. Installing the CUDA build of torch."),
        ["log.cudaTorchFailed"] = E("[warn] CUDA 版 torch の有効化に失敗しました。必要なら手動でインストールしてください。", "[warn] Failed to enable the CUDA build of torch. Install it manually if needed."),
        ["log.skipCompletedStep"] = E("[skip] {0}（既に完了）", "[skip] {0} (already completed)"),
        ["log.reuseNormalForEro"] = E("  manual ero が未設定のため normal の範囲を再利用します。", "  No manual ero range is set, so the normal range will be reused."),
        ["log.uabeaClassdataExists"] = E("UABEA classdata.tpk は既に存在します。", "UABEA classdata.tpk already exists."),
        ["log.uabeaClassdataReady"] = E("UABEA classdata.tpk を取得しました。", "Fetched UABEA classdata.tpk."),
        ["log.vgmstreamExists"] = E("vgmstream-cli.exe は既に存在します。", "vgmstream-cli.exe already exists."),
        ["log.vgmstreamReady"] = E("vgmstream-cli.exe を取得しました。", "Fetched vgmstream-cli.exe."),
        ["log.ffmpegExists"] = E("ffmpeg は既に存在します。", "ffmpeg already exists."),
        ["log.ffmpegReady"] = E("ffmpeg を取得しました。", "Fetched ffmpeg."),
        ["log.assetsToolsNetOverrideUsed"] = E("AssetsTools.NET.dll のビルド参照に環境変数のパスを使用します: {0}", "Using the environment-provided AssetsTools.NET.dll for source build: {0}"),
        ["log.modsTemplateGenerated"] = E("最小構成の mods_template を生成しました。", "Generated a minimal mods_template."),
        ["log.runtimePluginSkipped"] = E("runtime plugin ({0}) が見つからないためスキップします。", "Runtime plugin ({0}) was not found, so it will be skipped."),
        ["log.settingsLoadFailed"] = E("[warn] 設定の読み込みに失敗しました: {0}", "[warn] Failed to load settings: {0}"),
        ["log.settingsSaveFailed"] = E("[warn] 設定の保存に失敗しました: {0}", "[warn] Failed to save settings: {0}"),
        ["log.extractCompletedShort"] = E("[4/4] データ抽出完了", "[4/4] Data extraction completed"),
        ["log.deployToBackup"] = E("[1/1] バックアップ環境へ配備", "[1/1] Deploying to the backup environment"),
        ["log.previewExtractFsb"] = E("[preview/1] /etc 音声 (.fsb) を抽出", "[preview/1] Extracting /etc audio (.fsb)"),
        ["log.previewConvertWav"] = E("[preview/2] /etc .fsb -> .wav 変換", "[preview/2] Converting /etc .fsb -> .wav"),
        ["log.previewPrepareStyle"] = E("[preview/3] サンプル音声から style wav を作成", "[preview/3] Preparing style wav files from the samples"),
        ["log.previewSeedVc"] = E("[preview/4] Seed-VC で試聴を生成", "[preview/4] Running the Seed-VC preview conversion"),
        ["log.extractStep1"] = E("[1/8] 抽出元 HS2 から音声 (.fsb) を抽出", "[1/8] Extracting audio (.fsb) from the source HS2"),
        ["log.extractStep2"] = E("[2/8] vgmstream で .fsb -> .wav 変換", "[2/8] Converting .fsb -> .wav with vgmstream"),
        ["log.extractStep3"] = E("[3/8] routing manifest を生成", "[3/8] Building the routing manifest"),
        ["log.buildStep4"] = E("[4/8] サンプル音声から style wav を作成", "[4/8] Preparing style wav files from the samples"),
        ["log.styleInputChanged"] = E("  サンプル音声が変わったため style wav を再作成します。", "  Rebuilding style wav files because the sample input changed."),
        ["log.skipRebuildArtifacts"] = E("[skip] 06_rebuild（既存の成果物を再利用）", "[skip] 06_rebuild (reusing existing artifacts)"),
        ["log.buildStep6"] = E("[6/8] 変換済み wav から unity3d を再構築", "[6/8] Rebuilding unity3d bundles from converted wav files"),
        ["log.skipSplitArtifacts"] = E("[skip] 07_split（既存の成果物を再利用）", "[skip] 07_split (reusing existing artifacts)"),
        ["log.buildStep7"] = E("[7/8] split zipmod を生成", "[7/8] Building split zipmods"),
        ["log.buildStep8Deploy"] = E("[8/8] バックアップ環境へ配備", "[8/8] Deploying to the backup environment"),
        ["log.buildStep8Skip"] = E("[8/8] 配備をスキップ", "[8/8] Skipping deployment"),
        ["log.buildStep5SeedVc"] = E("[5/8] Seed-VC {0} 変換", "[5/8] Seed-VC {0} conversion"),
        ["log.seedSignatureChanged"] = E("  SeedVC 設定署名が変わったため、出力を再作成します。", "  Rebuilding outputs because the SeedVC settings signature changed."),
        ["log.sampleSignatureChanged"] = E("  サンプル署名が変わったため、出力を再作成します。", "  Rebuilding outputs because the sample signature changed."),
        ["log.skipSeedVcPendingZero"] = E("  pending=0 のため Seed-VC をスキップします。明示的な再作成時のみ再実行します。", "  Skipping Seed-VC because pending=0. It runs again only for explicit rebuilds."),
        ["log.resumeSeedVcPendingOnly"] = E("  サンプル署名が一致しているため、pending のみ再開します: pending={0}", "  Sample signatures match, so only pending items will be resumed: pending={0}"),
        ["log.undeployPersonality"] = E("[1/1] 配備済み zipmod / DLL を削除 (c{0})", "[1/1] Removing deployed zipmods / DLL (c{0})"),
        // Core runtime and validation errors
        ["error.sampleFileNotFound"] = E("サンプル音声ファイルが見つかりません。", "The sample audio file was not found."),
        ["error.normalSampleMissing"] = E("normal サンプル音声が未設定です。サンプル音声ダイアログで追加して割り当ててください。", "The normal sample audio is not assigned. Add it and assign it in the Sample Audio dialog."),
        ["error.manifestNotFound"] = E("manifest が見つかりません: {0}", "Manifest not found: {0}"),
        ["error.waveformZeroLength"] = E("音声の長さが 0 秒のため、波形を解析できません。", "Waveform analysis failed because the audio length is zero."),
        ["error.playSelectionNeedsFfmpeg"] = E("選択範囲を再生するには ffmpeg が必要です。先に依存セットアップを実行してください。", "Playing a selection requires ffmpeg. Run dependency setup first."),
        ["error.previewClipBuildFailed"] = E("試聴用クリップの生成に失敗しました。", "Failed to generate the preview clip."),
        ["error.waveformConversionFailed"] = E("波形用の変換に失敗しました: {0}", "Waveform conversion failed: {0}"),
        ["error.waveformNeedsFfmpeg"] = E("波形解析には ffmpeg が必要です。先に依存セットアップを実行してください。", "Waveform analysis requires ffmpeg. Run dependency setup first."),
        ["error.notRiffWav"] = E("RIFF 形式の WAV ではありません。", "The file is not a RIFF WAV."),
        ["error.notWaveFormat"] = E("WAVE ヘッダーがありません。", "The file does not contain a WAVE header."),
        ["error.invalidWavChunk"] = E("WAV チャンク構造が不正です。", "The WAV chunk layout is invalid."),
        ["error.missingWavDataChunk"] = E("WAV の data チャンクが見つかりません。", "The WAV data chunk was not found."),
        ["error.invalidWavFormat"] = E("WAV フォーマット情報が不正です。", "The WAV format block is invalid."),
        ["error.unsupportedWavFormat"] = E("未対応の WAV フォーマットです: format={0}, bits={1}", "Unsupported WAV format: format={0}, bits={1}"),
        ["error.unsupportedPcmBits"] = E("未対応の PCM ビット深度です: {0}", "Unsupported PCM bit depth: {0}"),
        ["error.wavMissingRiffHeader"] = E("WAV 解析に失敗しました。RIFF ヘッダーがありません。", "WAV parse failed: the RIFF header is missing."),
        ["error.wavMissingWaveHeader"] = E("WAV 解析に失敗しました。WAVE ヘッダーがありません。", "WAV parse failed: the WAVE header is missing."),
        ["error.pythonMissing"] = E("python.exe が見つかりません。", "python.exe was not found."),
        ["error.embeddedPythonExtractFailed"] = E("同梱 Python の展開に失敗しました。", "Failed to extract the bundled Python distribution."),
        ["error.invalidZipPath"] = E("zip に不正なパスが含まれています。", "The zip archive contains an invalid path."),
        ["error.styleWavBuildFailed"] = E("style wav の生成に失敗しました。", "Failed to build the style wav files."),
        ["error.ffmpegMissing"] = E("ffmpeg.exe が見つかりません。先に依存セットアップを実行してください。", "ffmpeg.exe was not found. Run dependency setup first."),
        ["error.styleSourceMissing"] = E("style 抽出元ファイルが見つかりません。", "The style extraction source file was not found."),
        ["error.styleRangeTooShort"] = E("style 範囲が短すぎます。0.2 秒より長く指定してください。", "The style range is too short. Use a duration longer than 0.2 seconds."),
        ["error.targetBundleResolveFailed"] = E("relative_path から対象 bundle を特定できません: {0}", "Could not resolve the target bundle from relative_path: {0}"),
        ["error.bundleDirectoryNotFound"] = E("音声 bundle ディレクトリが見つかりません: {0}", "Audio bundle directory was not found: {0}"),
        ["error.bundleNotFound"] = E("音声 bundle が見つかりません: {0}", "Audio bundle was not found: {0}"),
        ["personality.00"] = E("クール", "Composed"),
        ["personality.01"] = E("普通", "Normal"),
        ["personality.02"] = E("苦労人", "Hardworking"),
        ["personality.03"] = E("女友達", "Girlfriend"),
        ["personality.04"] = E("ギャル", "Fashionable"),
        ["personality.05"] = E("気弱", "Timid"),
        ["personality.06"] = E("母性的", "Motherly"),
        ["personality.07"] = E("ドS", "Sadistic"),
        ["personality.08"] = E("オープン", "Open-Minded"),
        ["personality.09"] = E("天然", "Airhead"),
        ["personality.10"] = E("几帳面", "Careful"),
        ["personality.11"] = E("大和撫子", "Ideal Japanese"),
        ["personality.12"] = E("ボーイッシュ", "Tomboy"),
        ["personality.13"] = E("ヤンデレ", "Obsessed"),
        ["seedvc.dialog.title"] = E("SeedVC 設定", "SeedVC Settings"),
        ["seedvc.category.engine"] = E("00 エンジン", "00 Engine"),
        ["seedvc.category.basic"] = E("01 基本パラメータ", "01 Basic Parameters"),
        ["seedvc.category.nr"] = E("02 ノイズ低減（NR）", "02 Noise Reduction (NR)"),
        ["seedvc.category.harsh"] = E("03 高域ざらつき補正", "03 Harsh High-Frequency Fix"),
        ["seedvc.category.breath"] = E("04 ブレス保護", "04 Breath Protection"),
        ["seedvc.category.globalHf"] = E("05 全体高域ブレンド", "05 Global HF Blend"),
        ["seedvc.category.deesser"] = E("06 ディエッサー", "06 De-Esser"),
        ["seedvc.category.audiosr"] = E("07 AudioSR", "07 AudioSR"),
        ["seedvc.engine.display"] = E("Engine（使用する SeedVC エンジン）", "Engine (SeedVC engine to use)"),
        ["seedvc.engine.description"] = E("v1 は安定性重視、v2 は表現力重視です。", "v1 generally favors stability, while v2 generally favors expressiveness."),
        ["seedvc.diffusionSteps.display"] = E("DiffusionSteps（拡散ステップ数）", "DiffusionSteps (number of diffusion steps)"),
        ["seedvc.diffusionSteps.description"] = E("低いほど高速、高いほど品質寄りになる傾向があります。", "Lower values are faster. Higher values may improve quality."),
        ["seedvc.lengthAdjust.display"] = E("LengthAdjust（長さ補正）", "LengthAdjust (duration adjustment)"),
        ["seedvc.lengthAdjust.description"] = E("1.0 で元音声と同じ長さです。", "1.0 keeps the source duration."),
        ["seedvc.intelligibility.display"] = E("IntelligibilityCfgRate（明瞭さ優先度）", "IntelligibilityCfgRate (intelligibility priority)"),
        ["seedvc.intelligibility.description"] = E("発音の明瞭さをどれだけ優先するかを調整します。", "Controls how strongly the model prioritizes intelligibility and articulation."),
        ["seedvc.similarity.display"] = E("SimilarityCfgRate（話者類似度優先度）", "SimilarityCfgRate (speaker similarity priority)"),
        ["seedvc.similarity.description"] = E("目標話者らしさをどれだけ強く反映するかを調整します。", "Controls how strongly the output is pulled toward the target speaker identity."),
        ["seedvc.topP.display"] = E("TopP（サンプリング上限）", "TopP (top-p sampling cutoff)"),
        ["seedvc.topP.description"] = E("生成候補の広さを調整します。低いほど保守的です。", "Controls the breadth of generation candidates. Lower values are more conservative."),
        ["seedvc.temperature.display"] = E("Temperature（生成多様性）", "Temperature (generation diversity)"),
        ["seedvc.temperature.description"] = E("声色や抑揚のばらつきを調整します。", "Controls variation in timbre and prosody during generation."),
        ["seedvc.repetitionPenalty.display"] = E("RepetitionPenalty（反復抑制）", "RepetitionPenalty (repetition penalty)"),
        ["seedvc.repetitionPenalty.description"] = E("不自然な反復を抑えます。1.0 で無効です。", "Reduces unnatural repetition. Set to 1.0 to disable it."),
        ["seedvc.nrStylePre.display"] = E("NrStylePre（style 抽出前に NR）", "NrStylePre (apply NR before style extraction)"),
        ["seedvc.nrStylePre.description"] = E("style 抽出前に軽くノイズ低減をかけます。", "Applies light noise reduction before extracting the style reference."),
        ["seedvc.nrOutPost.display"] = E("NrOutPost（変換後に NR）", "NrOutPost (apply NR after conversion)"),
        ["seedvc.nrOutPost.description"] = E("変換後のざらつきやノイズを軽減します。", "Applies post-conversion noise reduction to reduce harsh artifacts."),
        ["seedvc.nrStylePropDecrease.display"] = E("NrStylePropDecrease（style 側 NR 量）", "NrStylePropDecrease (style-side NR amount)"),
        ["seedvc.nrStylePropDecrease.description"] = E("style 側の NR の強さです。強すぎると音の輪郭が痩せます。", "Strength of style-side NR. Too much can thin consonants and detail."),
        ["seedvc.nrOutPropDecrease.display"] = E("NrOutPropDecrease（出力側 NR 量）", "NrOutPropDecrease (output-side NR amount)"),
        ["seedvc.nrOutPropDecrease.description"] = E("変換後にかける NR の強さです。強すぎると空気感が失われます。", "Strength of output-side NR. Too much can remove natural air and ambience."),
        ["seedvc.nrTimeMaskSmoothMs.display"] = E("NrTimeMaskSmoothMs（時間方向スムージング[ms]）", "NrTimeMaskSmoothMs (time-axis smoothing [ms])"),
        ["seedvc.nrTimeMaskSmoothMs.description"] = E("時間方向のマスクをどれだけ滑らかにするかを指定します。", "Smooths the NR mask over time."),
        ["seedvc.nrFreqMaskSmoothHz.display"] = E("NrFreqMaskSmoothHz（周波数方向スムージング[Hz]）", "NrFreqMaskSmoothHz (frequency-axis smoothing [Hz])"),
        ["seedvc.nrFreqMaskSmoothHz.description"] = E("周波数方向のマスクをどれだけ滑らかにするかを指定します。", "Smooths the NR mask across frequency."),
        ["seedvc.harshFix.display"] = E("HarshFix（高域ざらつき補正）", "HarshFix (harsh HF fix)"),
        ["seedvc.harshFix.description"] = E("ブレスや笑い声の硬い高域を抑える後処理です。", "Post-processing that reduces brittle high-frequency artifacts in breaths and laughter."),
        ["seedvc.harshHfCutoff.display"] = E("HarshHfCutoff（補正開始周波数[Hz]）", "HarshHfCutoff (HF cutoff [Hz])"),
        ["seedvc.harshHfCutoff.description"] = E("高域補正を開始する目安の周波数です。", "Approximate frequency where the harsh-HF correction begins."),
        ["seedvc.harshSrcHfMix.display"] = E("HarshSrcHfMix（元音声高域の混合率）", "HarshSrcHfMix (source HF mix)"),
        ["seedvc.harshSrcHfMix.description"] = E("元音声の高域成分をどれだけ戻すかを調整します。", "Controls how much of the source high-frequency content is blended back in."),
        ["seedvc.harshOverFactor.display"] = E("HarshOverFactor（過補正係数）", "HarshOverFactor (over-correction factor)"),
        ["seedvc.harshOverFactor.description"] = E("ざらつきを検出した部分に対する抑制の強さです。", "Controls how strongly harsh segments are attenuated once detected."),
        ["seedvc.harshFlatnessTh.display"] = E("HarshFlatnessTh（平坦度しきい値）", "HarshFlatnessTh (flatness threshold)"),
        ["seedvc.harshFlatnessTh.description"] = E("ざらつき区間の判定に使うスペクトル平坦度のしきい値です。", "Spectral flatness threshold used to detect harsh segments."),
        ["seedvc.harshMinSegmentMs.display"] = E("HarshMinSegmentMs（最小区間[ms]）", "HarshMinSegmentMs (minimum segment [ms])"),
        ["seedvc.harshMinSegmentMs.description"] = E("補正対象と見なす最小区間長です。", "Minimum segment length that qualifies for harsh-HF correction."),
        ["seedvc.breathPassThrough.display"] = E("BreathPassThrough（ブレス保護）", "BreathPassThrough (breath protection)"),
        ["seedvc.breathPassThrough.description"] = E("ブレスや息成分を元音声寄りに保護します。", "Preserves breath-heavy regions by keeping them closer to the source."),
        ["seedvc.breathFlatnessTh.display"] = E("BreathFlatnessTh（平坦度しきい値）", "BreathFlatnessTh (flatness threshold)"),
        ["seedvc.breathFlatnessTh.description"] = E("ブレス区間の判定に使う平坦度しきい値です。", "Spectral flatness threshold used to detect breath-like regions."),
        ["seedvc.breathRmsMax.display"] = E("BreathRmsMax（最大 RMS）", "BreathRmsMax (maximum RMS)"),
        ["seedvc.breathRmsMax.description"] = E("ブレスと見なす最大音量の目安です。", "Maximum RMS level still treated as a breath-like region."),
        ["seedvc.breathMix.display"] = E("BreathMix（元音声混合率）", "BreathMix (source mix amount)"),
        ["seedvc.breathMix.description"] = E("ブレス区間で元音声をどれだけ混ぜるかを指定します。", "Controls how much of the source is mixed back into detected breath regions."),
        ["seedvc.globalHfBlend.display"] = E("GlobalHfBlend（全体高域ブレンド）", "GlobalHfBlend (global HF blend)"),
        ["seedvc.globalHfBlend.description"] = E("全体に元音声の高域を少し戻して輪郭を補います。", "Blends a small amount of source high-frequency content back into the whole output."),
        ["seedvc.globalHfCutoff.display"] = E("GlobalHfCutoff（高域開始周波数[Hz]）", "GlobalHfCutoff (HF cutoff [Hz])"),
        ["seedvc.globalHfCutoff.description"] = E("高域ブレンドを開始する周波数です。", "Frequency above which the global HF blend is applied."),
        ["seedvc.globalHfSrcMix.display"] = E("GlobalHfSrcMix（元音声高域の混合率）", "GlobalHfSrcMix (source HF mix)"),
        ["seedvc.globalHfSrcMix.description"] = E("全体ブレンドで戻す元音声高域の割合です。", "Amount of source high-frequency content mixed in by the global HF blend."),
        ["seedvc.globalDeEsser.display"] = E("GlobalDeEsser（ディエッサー）", "GlobalDeEsser (de-esser)"),
        ["seedvc.globalDeEsser.description"] = E("歯擦音の強すぎる高域を抑えます。", "Reduces overly sharp sibilant high frequencies."),
        ["seedvc.deEsserLowHz.display"] = E("DeEsserLowHz（下限周波数[Hz]）", "DeEsserLowHz (low cutoff [Hz])"),
        ["seedvc.deEsserLowHz.description"] = E("ディエッサーを適用する帯域の下限です。", "Lower bound of the frequency band processed by the de-esser."),
        ["seedvc.deEsserHighHz.display"] = E("DeEsserHighHz（上限周波数[Hz]）", "DeEsserHighHz (high cutoff [Hz])"),
        ["seedvc.deEsserHighHz.description"] = E("ディエッサーを適用する帯域の上限です。", "Upper bound of the frequency band processed by the de-esser."),
        ["seedvc.deEsserStrength.display"] = E("DeEsserStrength（強さ）", "DeEsserStrength (strength)"),
        ["seedvc.deEsserStrength.description"] = E("歯擦音を抑える強さです。強すぎるとこもった音になります。", "Amount of sibilant reduction. Too much can make the output sound dull."),
        ["seedvc.audioSrPost.display"] = E("AudioSrPost（変換後に AudioSR）", "AudioSrPost (apply AudioSR after conversion)"),
        ["seedvc.audioSrPost.description"] = E("SeedVC の変換後に AudioSR を使って音質補正を行います。", "Applies AudioSR-based enhancement after SeedVC conversion."),
        ["error.previewWavMissing"] = E("preview wav が見つかりません。", "The preview wav file was not found."),
        ["error.sampleSourceNotFound"] = E("サンプル元ファイルが見つかりません。", "The sample source file was not found."),
        ["error.sampleRangeNeedsFfmpeg"] = E("範囲切り出しには ffmpeg が必要です。先に依存セットアップを実行してください。", "ffmpeg is required for range extraction. Run dependency setup first."),
        ["error.sampleRangeExtractionFailed"] = E("サンプル切り出しに失敗しました。", "Failed to extract the sample clip."),
        ["error.sampleImportNeedsFfmpeg"] = E("WAV 以外の音声を取り込むには ffmpeg が必要です。先に依存セットアップを実行してください。", "ffmpeg is required to import non-WAV files. Run dependency setup first."),
        ["error.sampleImportFailed"] = E("サンプルの取り込みに失敗しました。", "Failed to import the sample clip."),
        ["error.normalSampleMissingFile"] = E("normal サンプル音声ファイルが見つかりません。", "The normal sample audio file was not found."),
        ["error.eroSampleMissingFile"] = E("ero サンプル音声ファイルが見つかりません。", "The ero sample audio file was not found."),
        ["error.dependencyRootMissing"] = E("依存ルートが見つかりません。外部ツールルートを指定するか、アプリの横に runtime_bundle を配置してください。", "No dependency root is available. Specify an external tools root or place a runtime_bundle next to the app."),
        ["error.personalitySourceMissing"] = E("対象性格のソースが見つかりません: {0}", "The target personality source was not found: {0}"),
        ["error.dependencyFileMissing"] = E("依存ファイルが不足しています: {0}（外部ルートと同梱ルートの両方を確認しました）", "Missing dependency file: {0} (checked both the external and bundled roots)."),
        ["error.deployToProductionForbidden"] = E("保護対象として扱われる本番環境への配備は禁止です。", "Deploying to the protected production environment is forbidden."),
        ["error.inputWavMissing"] = E("入力 WAV が見つかりません。", "The input WAV file was not found."),
        ["error.inputWavMustBeWav"] = E("入力には .wav ファイルを指定してください。", "The input must be a .wav file."),
        ["error.modelBucketInvalid"] = E("model bucket は normal または ero のみ指定できます。", "The model bucket must be either normal or ero."),
        ["error.fullRunRootMissing"] = E("全量 run ルートが見つかりません: {0}", "The full-run root was not found: {0}"),
        ["error.routingManifestMissing"] = E("routing manifest が見つかりません: {0}", "The routing manifest was not found: {0}"),
        ["error.previewEtcBundleMissing"] = E("preview 用の /etc bundle を特定できません。", "Could not resolve the /etc preview bundle."),
        ["error.previewFsbMissing"] = E("preview 用に抽出された .fsb がありません。", "No preview .fsb files were extracted."),
        ["error.extractArtifactsMissing"] = E("抽出成果物が不足しています。先に「データ抽出」を実行してください。", "Extracted data is incomplete. Run data extraction first."),
        ["error.extractedFsbMissing"] = E("抽出結果に .fsb がありません。", "No .fsb files were produced by extraction."),
        ["error.bundleSelectionChangedReextract"] = E("抽出済み bundle の選択状態が現在の設定と一致しません。先にデータ抽出をやり直してください。", "The extracted bundle selection does not match the current configuration. Re-run data extraction first."),
        ["error.deployZipmodsMissing"] = E("配備に使う zipmod がありません。先に全量変換を実行してください。", "No zipmods are available to deploy. Run the full conversion first."),
        ["error.uabeaClassdataMissing"] = E("UABEA 配布物から classdata.tpk を見つけられませんでした。", "Could not find classdata.tpk in the UABEA package."),
        ["error.uabeaReleaseApiInvalid"] = E("UABEA release API の応答が不正です。", "The UABEA release API response is invalid."),
        ["error.uabeaReleaseZipNotFound"] = E("UABEA の配布 zip を特定できませんでした。HS2VR_UABEA_ZIP_URL を設定してください。", "Could not locate a UABEA release zip. Set HS2VR_UABEA_ZIP_URL."),
        ["error.vgmstreamCliMissing"] = E("vgmstream 配布物から vgmstream-cli.exe を見つけられませんでした。", "Could not find vgmstream-cli.exe in the vgmstream package."),
        ["error.ffmpegBinaryMissing"] = E("ffmpeg 配布物から ffmpeg.exe を見つけられませんでした。", "Could not find ffmpeg.exe in the ffmpeg package."),
        ["error.ffprobeBinaryMissing"] = E("ffmpeg 配布物から ffprobe.exe を見つけられませんでした。", "Could not find ffprobe.exe in the ffmpeg package."),
        ["error.ffmpegReleaseApiInvalid"] = E("ffmpeg release API の応答が不正です。", "The ffmpeg release API response is invalid."),
        ["error.ffmpegReleaseZipNotFound"] = E("ffmpeg の配布 zip を特定できませんでした。HS2VR_FFMPEG_ZIP_URL を設定してください。", "Could not locate an ffmpeg release zip. Set HS2VR_FFMPEG_ZIP_URL."),
        ["error.vgmstreamReleaseApiInvalid"] = E("vgmstream release API の応答が不正です。", "The vgmstream release API response is invalid."),
        ["error.vgmstreamReleaseZipNotFound"] = E("vgmstream の配布 zip を特定できませんでした。HS2VR_VGMSTREAM_ZIP_URL を設定してください。", "Could not locate a vgmstream release zip. Set HS2VR_VGMSTREAM_ZIP_URL."),
        ["error.assetsToolsNetMissingForPatcherBuild"] = E("AssetsTools.NET.dll が見つかりません。このリポジトリには同梱していません。`{0}` に配置するか、`{1}` を設定してから依存セットアップを実行してください。", "AssetsTools.NET.dll was not found. This repository does not vendor it. Place it at `{0}` or set `{1}` before running dependency setup."),
        ["error.requiredScriptMissing"] = E("必要なスクリプトを配置できませんでした: {0}", "Could not obtain the required script: {0}"),
        ["error.uabAudioClipPatcherMissing"] = E("UabAudioClipPatcher.exe を配置できませんでした。", "Could not obtain UabAudioClipPatcher.exe."),
        ["error.convertedWavDirectoryMissing"] = E("変換済み wav ディレクトリが存在しません: {0}", "Converted wav directory does not exist: {0}"),
        ["error.convertedWavPersonalityMismatch"] = E("変換済み wav の性格 ID が対象 c{0} と一致しません: {1} (total={2}, matched={3})。run_root と対象性格の組み合わせを確認してください。", "Converted wav personality IDs do not match the target c{0}: {1} (total={2}, matched={3}). Check the run_root and target personality combination."),
        ["error.seedVcFailedWithReport"] = E("Seed-VC 変換で失敗しました。report={0}", "Seed-VC conversion failed. report={0}"),
        ["error.seedVcFailedWithoutReport"] = E("Seed-VC 変換プロセスの起動に失敗しました。report は生成されていません。detail={0}", "Failed to start the Seed-VC conversion process. No report was generated. detail={0}"),
        ["error.deployTargetMissing"] = E("配備先 HS2 フォルダが見つかりません: {0}", "The deploy HS2 folder was not found: {0}"),
        ["error.productionEnvironmentProtected"] = E("保護対象の本番環境は変更禁止です。バックアップ環境のみを使用してください。", "The protected production environment must not be modified. Use only the backup environment."),
        ["error.singleRebuildOutputMissing"] = E("単体再作成の出力が見つかりません。report={0}", "The single-file reconversion output was not found. report={0}"),
        ["error.partialRebuildOutputMissing"] = E("部分再作成の出力が見つかりません: {0}", "The partial rebuild output was not found: {0}"),
        ["error.relativePathEmpty"] = E("relative_path が空です。", "relative_path is empty."),
        ["error.relativePathMissingInManifest"] = E("manifest に relative_path が見つかりません: {0}", "relative_path was not found in the manifest: {0}"),
        ["error.rebuildSourceMissing"] = E("再作成元の音声が見つかりません。relative_path={0}; checked={1}", "The rebuild source audio was not found. relative_path={0}; checked={1}"),
        ["error.partialInputNotInRun"] = E("入力 WAV がこの全量 run に属していません。run_root 配下の voice_extract_wav または voice_replace_wav を選択してください。", "The input WAV does not belong to this full run. Select a WAV under run_root/voice_extract_wav or run_root/voice_replace_wav."),
        ["error.partialSourceMissing"] = E("入力 WAV に対応する source_file が見つかりません。", "The source_file corresponding to the input WAV was not found."),
        ["error.pipelinePythonMissing"] = E("Python が見つかりません。外部ツールルート配下に python/python.exe または rvc_venv/*/python.exe を配置してください。", "Python was not found. Place python/python.exe or rvc_venv/*/python.exe under the external tools root."),
        ["error.previewEtcWavMissing"] = E("preview 用の /etc wav を抽出できませんでした。", "Could not extract any /etc wav files for preview."),
        ["error.seedVcChunkFailed"] = E("Seed-VC chunk の実行に失敗しました。chunk={0}, manifest={1}, report={2}", "Seed-VC chunk execution failed. chunk={0}, manifest={1}, report={2}"),
    };

    public static string Get(string key) => Get(LocalizationState.CurrentLanguage, key);

    public static string Get(UiLanguage language, string key)
    {
        if (!Entries.TryGetValue(key, out var entry))
            return $"[[{key}]]";

        return language == UiLanguage.En ? entry.En : entry.Ja;
    }

    public static string Get(UiLanguage language, string key, params object[] args)
    {
        var format = Get(language, key);
        return args == null || args.Length == 0
            ? format
            : string.Format(CultureInfo.CurrentCulture, format, args);
    }

    public static string Get(string key, params object[] args)
        => Get(LocalizationState.CurrentLanguage, key, args);
}

// Exposes the current UI language to components that are instantiated outside the main form,
// such as PropertyGrid metadata providers.
internal static class LocalizationState
{
    public static UiLanguage CurrentLanguage { get; set; } = UiLanguage.Ja;
}

